create table Persons (
    id SERIAL PRIMARY KEY,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	address VARCHAR(50),
	state VARCHAR(50),
	city VARCHAR(50),
	zip VARCHAR(50),
	phone VARCHAR(50)
);
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Gael', 'Salsbury', 'Norbury', 'MN', 'Maple Plain', '55572', '763-861-3618');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Austina', 'Boothebie', 'Mc Kellen', 'IN', 'Fort Wayne', '46805', '260-597-5882');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Flo', 'Shinner', 'Wrightson', 'SC', 'Beaufort', '29905', '843-455-5279');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Amalee', 'Flatman', 'Gorler', 'LA', 'Baton Rouge', '70894', '225-242-1221');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Hyacinthia', 'Ruter', 'Lamberto', 'TX', 'Austin', '78764', '512-381-7897');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Linus', 'Peasee', 'Krook', 'CA', 'Modesto', '95354', '209-139-7181');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Flory', 'Wasson', 'Flury', 'CA', 'North Hollywood', '91606', '818-569-7385');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Waring', 'Pascoe', 'Guiduzzi', 'OH', 'Akron', '44329', '330-678-1733');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Travis', 'Syder', 'Vanyatin', 'FL', 'Bradenton', '34205', '941-841-6470');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Erma', 'Trimbey', 'Joselovitch', 'VA', 'Springfield', '22156', '571-822-4157');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Chadd', 'Cicchinelli', 'Bartzen', 'GA', 'Atlanta', '30328', '770-399-0846');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Fredrick', 'Astin', 'Bossom', 'TX', 'Tyler', '75799', '903-249-2157');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Toinette', 'Smallpeice', 'Shaves', 'FL', 'Miami', '33111', '786-771-9007');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Ekaterina', 'Vaneschi', 'Westoff', 'VA', 'Chesapeake', '23324', '757-161-5219');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Bibbie', 'Hentzeler', 'Caneo', 'CA', 'Torrance', '90510', '818-949-6783');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Zita', 'Buffy', 'Tetla', 'OH', 'Canton', '44705', '330-624-0603');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Melessa', 'Noot', 'Longmire', 'CA', 'San Jose', '95133', '408-717-0665');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Huntlee', 'Casetti', 'Hallows', 'OH', 'Cleveland', '44177', '216-871-2234');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Alic', 'Millen', 'Adams', 'CA', 'Modesto', '95397', '209-211-7926');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Ashby', 'Highwood', 'Wabersinke', 'TN', 'Memphis', '38136', '901-424-8762');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Meriel', 'Readie', 'Keson', 'TX', 'San Antonio', '78250', '210-191-6709');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Barbette', 'Vales', 'Brideoke', 'FL', 'Miami', '33245', '786-800-5671');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Kaiser', 'Milsom', 'Dragonette', 'CA', 'San Diego', '92121', '619-775-7650');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Zsa zsa', 'Effnert', 'Puttick', 'IL', 'Peoria', '61614', '309-913-7261');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Towney', 'Ledwidge', 'Castagnaro', 'MO', 'Columbia', '65211', '573-440-1489');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Hill', 'Oleszcuk', 'Cardno', 'CA', 'Sacramento', '94263', '916-402-5377');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Dorena', 'Creffeild', 'Adnams', 'CT', 'Hartford', '06183', '860-466-6176');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Quentin', 'Sapsforde', 'Patty', 'FL', 'Pensacola', '32520', '850-249-3831');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Vonni', 'Whitwham', 'Faas', 'KS', 'Topeka', '66622', '785-309-5161');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Paula', 'Chotty', 'Becker', 'OH', 'Canton', '44720', '234-174-0789');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Maudie', 'Cavie', 'Hullbrook', 'TX', 'Austin', '78710', '512-402-7603');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Glenine', 'Dudeney', 'Jowsey', 'FL', 'Miami', '33261', '305-129-1106');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Rey', 'Wheelband', 'Evison', 'AZ', 'Phoenix', '85005', '480-495-8582');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Emlynn', 'Goddman', 'Bernadon', 'NM', 'Albuquerque', '87201', '505-104-7391');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Teodorico', 'Gilling', 'Inderwick', 'IN', 'Indianapolis', '46239', '317-545-5312');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Bond', 'Hakes', 'Tomaini', 'IN', 'Evansville', '47732', '812-163-9169');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Elisha', 'Abrahamson', 'Durtnall', 'WI', 'Madison', '53716', '608-798-8154');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Sven', 'Mewha', 'Beddall', 'IN', 'Terre Haute', '47812', '812-970-1608');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Franny', 'Imos', 'Nobles', 'TX', 'Houston', '77212', '713-201-8637');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Gretta', 'Bentham', 'Petroff', 'TX', 'San Antonio', '78250', '210-752-4986');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Mina', 'Swayland', 'Geraldez', 'NY', 'Jamaica', '11470', '718-390-1898');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Coralyn', 'Minkin', 'Hedgeley', 'WV', 'Charleston', '25305', '304-350-0304');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Brande', 'Meddings', 'Sadry', 'TX', 'Houston', '77255', '713-188-6021');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Viviyan', 'Osbourne', 'Adelman', 'NE', 'Omaha', '68105', '402-696-9282');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Roobbie', 'Dunbabin', 'Niccols', 'NJ', 'Newark', '07195', '862-951-0476');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Minnaminnie', 'Hauxby', 'Delaney', 'IN', 'Gary', '46406', '219-816-0158');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Martita', 'Busse', 'Blazewicz', 'PA', 'Philadelphia', '19184', '215-491-5448');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Jamima', 'McNiven', 'Have', 'DC', 'Washington', '20268', '202-174-9177');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Tyler', 'Pettwood', 'Bremond', 'MI', 'Detroit', '48267', '313-787-7179');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Scottie', 'Haverson', 'Thumann', 'TX', 'Houston', '77035', '713-504-8111');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Nikkie', 'Gimson', 'Southers', 'OH', 'Lima', '45807', '419-101-7204');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Patricio', 'Mould', 'Eastlake', 'TN', 'Knoxville', '37924', '865-597-2133');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Udale', 'Andras', 'Popplestone', 'SC', 'Charleston', '29424', '843-869-9039');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Petronella', 'Canlin', 'Frankowski', 'OK', 'Oklahoma City', '73114', '405-989-5042');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Isabelita', 'Ziehm', 'O Sullivan', 'FL', 'Lakeland', '33811', '863-832-1797');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Gran', 'Hazle', 'Sandyfirth', 'NY', 'New York City', '10060', '646-997-8522');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Derrik', 'Goldsworthy', 'Ivakhnov', 'AZ', 'Tucson', '85754', '520-193-2940');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Sondra', 'Varty', 'McKeurtan', 'FL', 'Clearwater', '34615', '727-327-6340');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Darrin', 'Roke', 'Rosenvasser', 'AL', 'Mobile', '36605', '251-193-7144');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Halie', 'Seabert', 'Clyant', 'TX', 'Dallas', '75226', '903-890-2608');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Zeke', 'Wharby', 'Abramin', 'SC', 'Columbia', '29215', '803-666-9315');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Benedicto', 'Rees', 'Filewood', 'LA', 'New Orleans', '70165', '504-652-9492');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Ilyssa', 'Gobourn', 'Ellul', 'VA', 'Roanoke', '24009', '540-254-6148');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Sherie', 'Hugh', 'Jirzik', 'CO', 'Aurora', '80045', '303-584-6154');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Aurie', 'Tessyman', 'Guiness', 'NY', 'Buffalo', '14215', '716-921-7273');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Electra', 'Marchiso', 'MacGinley', 'TX', 'Amarillo', '79171', '806-545-0446');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Maureen', 'Widdowfield', 'Speaks', 'FL', 'Tallahassee', '32309', '850-599-8911');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Hyman', 'Everson', 'Byrkmyr', 'CA', 'Pasadena', '91125', '626-878-5495');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Rivkah', 'Geistmann', 'Orknay', 'TN', 'Memphis', '38104', '615-966-9779');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Trude', 'Currington', 'Mechan', 'CA', 'Santa Barbara', '93150', '805-741-2954');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Moyna', 'Le Monnier', 'Scroggs', 'CA', 'San Luis Obispo', '93407', '805-330-7928');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Padget', 'Fridd', 'Frentz', 'NY', 'Albany', '12232', '518-906-1512');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Fons', 'Donnersberg', 'Battershall', 'LA', 'Shreveport', '71105', '318-277-0735');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Yvette', 'Rivaland', 'Hedingham', 'GA', 'Norcross', '30092', '770-939-9065');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Webb', 'Sieve', 'Londors', 'TX', 'San Antonio', '78265', '210-948-7641');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Marylee', 'Zelley', 'Matteucci', 'NY', 'Albany', '12227', '518-745-9752');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Rasia', 'Lages', 'McElwee', 'VA', 'Richmond', '23293', '804-712-0230');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Silvana', 'Lorrimer', 'Stooders', 'NM', 'Santa Fe', '87592', '505-290-4798');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Tomi', 'Wroath', 'Magnay', 'TX', 'Houston', '77070', '713-731-5070');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Pippy', 'Dandison', 'Baccas', 'OH', 'Toledo', '43699', '419-587-7099');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Nita', 'Tilt', 'Sowter', 'OK', 'Tulsa', '74126', '918-390-3756');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Cyndy', 'Artinstall', 'Milleton', 'TX', 'Austin', '78715', '512-724-1874');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Valerye', 'Swancott', 'Enser', 'IN', 'Indianapolis', '46239', '317-390-5369');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Garrot', 'Dewhurst', 'Gonzalo', 'CA', 'San Francisco', '94121', '858-123-5050');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Cesya', 'Chamney', 'Mitchelson', 'GA', 'Atlanta', '30356', '404-425-2589');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Lauritz', 'Abramski', 'Anthonsen', 'CT', 'Hartford', '06140', '860-264-8251');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Eadmund', 'Hawking', 'Shuter', 'IL', 'Rockford', '61110', '815-726-7334');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Poppy', 'Hassent', 'Yearnes', 'CA', 'Sacramento', '95813', '916-676-2317');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Vanya', 'Skeleton', 'Lodeke', 'DC', 'Washington', '20508', '202-425-6414');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Molly', 'Stickney', 'McIlmorie', 'MN', 'Saint Paul', '55188', '651-425-2403');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Judas', 'Blaksland', 'Grindell', 'NV', 'Reno', '89550', '775-574-8550');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Ephraim', 'Asplin', 'Cattemull', 'CA', 'San Diego', '92170', '619-987-8009');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Duffie', 'Von Helmholtz', 'Dahler', 'TX', 'Amarillo', '79105', '806-463-7873');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Donica', 'Haddinton', 'Maddinon', 'WV', 'Charleston', '25321', '304-449-7023');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Ellswerth', 'Chevin', 'Capper', 'CA', 'Corona', '92878', '951-117-8176');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Fin', 'Deelay', 'Arderne', 'FL', 'Miami', '33185', '305-913-9203');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Pepito', 'Maudett', 'Linster', 'NY', 'New York City', '10019', '646-658-9398');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Craggie', 'Benmore', 'Mackilpatrick', 'TX', 'Houston', '77240', '713-190-6106');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Prudence', 'Baglin', 'Trevithick', 'CA', 'Santa Rosa', '95405', '707-701-6328');
insert into Persons (first_name, last_name, address, state, city, zip, phone) values ('Dreddy', 'Lashford', 'Kings', 'OH', 'Toledo', '43610', '419-598-6876');
